version: '3.3'
services:
  graphql-server:
    container_name: graphql-server
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - db

#  db:
#    image: "mcr.microsoft.com/mssql/server"
#    environment:
#      SA_PASSWORD: "password"
#      ACCEPT_EULA: "Y"
#    ports:
#      - "2500:1433"
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'user'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'user'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  # Names our volume
volumes:
  my-db: