version: '3.3'
services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'user'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'user'
      MYSQL_TCP_PORT: '3307'
    ports:
      - '127.0.0.1:3307:3307'
  # Names our volume